# Default values for nvmesh-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: nvmesh-csi-driver
driverName: nvmesh-csi.excelero.com

#namespaceOverride: nvmesh-csi-driver
multipleCsiDrivers: false

features:
  ecVolumesEnabled: true

config:
  protocol: https
  servers: n115:4000
  # logLevel: DEBUG
  # sdkLogLevel: DEBUG
  # kubeClientLogLevel: INFO
  # use the format of <ip:port> or <hostname:port> pointing to your management server REST interface
  # To combine with nvmesh-management container in kubernetes, please use the following service reference for management.servers
  #management.servers: "nvmesh-management-svc.nvmesh.svc.cluster.local:4000"

  username: YWRtaW5AZXhjZWxlcm8uY29t
  password: YWRtaW4=

  attachIOEnabledTimeout: 30
  printStackTraces: false
  usePreempt: false

  # Uncomment 'topologyJsonFilePath' to add topology info to the ConfigMap
  # Please view and edit the topology.json file or provide a path for your own topology json
  # topologyJsonFilePath: topology.json

hostBinariesPath: /bin
systemdHost: false

defaultStorageClasses: true

controller:
  replicaCount: 1
  tolerations: []
  hostNetwork: false
  nodeSelector: {}
  affinity: {}
nodeDriver:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
      operator: Exists
  nodeSelector: {}
  affinity: {}

image:
  repository: excelero/nvmesh-csi-driver
  pullPolicy: IfNotPresent

pspEnabled: true

csiDriverRegistrar:
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v2.1.0
  pullPolicy: IfNotPresent

csiExternalProvisioner:
  repository: quay.io/k8scsi/csi-provisioner
  tag: v2.1.0
  pullPolicy: IfNotPresent

csiExternalAttacher:
  repository: quay.io/k8scsi/csi-attacher
  tag: v3.1.0
  pullPolicy: IfNotPresent

csiExternalResizer:
  repository: quay.io/k8scsi/csi-resizer
  tag: v1.1.0
  pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

# overrideKubeVersion - this is to workaround the missing flag --kube-version (https://github.com/helm/helm/issues/7326)
# we should use this only for templating (running `helm template ..`)
# usage `helm template ./nvmesh-csi-driver --set overrideKubeVersion=1.15
overrideKubeVersion: false
