# expected the following variables to be defined in GitLabs CI/CD Variables:
#   MANAGEMENT_SERVERS: "nvme115:4000"
#   KUBE_MASTER: "nvme115"

stages:
  - sanity
#  - integration

sanity:
  stage: sanity
  script:
    - pip2 install -r requirements.txt
    - cd test/
    - sudo ./run_sanity_tests.sh $MANAGEMENT_SERVERS
    - exit $?

# integration:
#   stage: integration
#   script:
#     - pwd
#     - cd test/
#     - ./run_integration_tests.sh --master $KUBE_MASTER
#     - exit $?
