apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  volumeBindingMode: Immediate
  resources:
    requests:
      storage: 8Gi
  storageClassName: nvmesh-concatenated