# First create a volume in the NVMesh Management software with the following attributes: capacity: 5Gi, Raid Type: RAID10, name: vol-1

# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: name-in-k8s
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  volumeMode: Block
  storageClassName: nvmesh-raid10
  csi:
    driver: nvmesh-csi.excelero.com
    volumeHandle: vol-1
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 5Gi
  storageClassName: nvmesh-raid10
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
      containers:
      - name: c-1
        image: alpine:3
        command: ["/bin/sh", "-c", "echo hello ; while true ; do sleep 1; done"]
        volumeDevices:
            - name: vol
              devicePath: /vol
      restartPolicy: Never
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-1