kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-config
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  management.protocol: {{ .Values.config.protocol }}
  management.servers: {{ .Values.config.servers }}
  attachIOEnabledTimeout: "{{ .Values.config.attachIOEnabledTimeout }}"
  printStackTraces: "{{ .Values.config.printStackTraces }}"
{{- if .Values.config.logLevel }}
  logLevel: {{ .Values.config.logLevel }}
{{- end }}
{{- if .Values.config.sdkLogLevel }}
  sdkLogLevel: {{ .Values.config.sdkLogLevel }}
{{- end }}
{{- if .Values.config.kubeClientLogLevel }}
  kubeClientLogLevel: {{ .Values.config.kubeClientLogLevel }}
{{- end }}
  csiConfigMapName: {{ template "nvmesh-csi-driver.fullname" . }}-config
  topologyConfigMapName: {{ template "nvmesh-csi-driver.fullname" . }}-topology
{{- if .Values.config.topologyJsonFilePath }}
  topology: |-
{{ printf .Values.config.topologyJsonFilePath | .Files.Get | indent 4 }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-topology
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  zones: "{}"
