kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-config
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
{{- if and (not .Values.config.topology) (not .Values.config.topologyJsonFilePath) }}
  management.protocol: {{ .Values.config.protocol }}
  management.servers: {{ .Values.config.servers }}
{{- end }}
  attachIOEnabledTimeout: "{{ .Values.config.attachIOEnabledTimeout }}"
  detachTimeout: "{{ .Values.config.detachTimeout }}"
  forceDetach: "{{ .Values.config.forceDetach }}"
  printStackTraces: "{{ .Values.config.printStackTraces }}"
  usePreempt: "{{ .Values.config.usePreempt }}"
{{- if .Values.config.logLevel }}
  logLevel: {{ .Values.config.logLevel }}
{{- end }}
{{- if .Values.config.sdkLogLevel }}
  sdkLogLevel: {{ .Values.config.sdkLogLevel }}
{{- end }}
{{- if .Values.config.kubeClientLogLevel }}
  kubeClientLogLevel: {{ .Values.config.kubeClientLogLevel }}
{{- end }}
{{- if .Values.config.grpcMaxWorkers }}
  grpcMaxWorkers: "{{ .Values.config.grpcMaxWorkers }}"
{{- end }}
{{- if .Values.config.sdkHttpRequestTimeout }}
  sdkHttpRequestTimeout: "{{ .Values.config.sdkHttpRequestTimeout }}"
{{- end }}
  csiConfigMapName: {{ template "nvmesh-csi-driver.fullname" . }}-config
  topologyConfigMapName: {{ template "nvmesh-csi-driver.fullname" . }}-topology
{{- if or .Values.config.topology .Values.config.topologyJsonFilePath }}
  topology: |-
{{- if .Values.config.topology }}
{{ .Values.config.topology | toPrettyJson | indent 4 }}
{{- else if .Values.config.topologyJsonFilePath }}
{{ printf .Values.config.topologyJsonFilePath | .Files.Get | indent 4 }}
{{- end }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-topology
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  zones: "{}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-compatibility
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  comp_matrix: |-
{{ printf .Values.config.versionMatrixJsonFilePath | .Files.Get | indent 4 }}
