kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-config
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  management.protocol: {{ .Values.config.protocol }}
  management.servers: {{ .Values.config.servers }}
  config: '{}'
