kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-config
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  management.protocol: {{ .Values.config.protocol }}
  management.servers: {{ .Values.config.servers }}
  attachIOEnabledTimeout: "{{ .Values.config.attachIOEnabledTimeout }}"
  printStackTraces: "{{ .Values.config.printStackTraces }}"
{{- if .Values.config.topologyJsonFilePath }}
  topology: |-
{{ printf .Values.config.topologyJsonFilePath | .Files.Get | indent 4 }}
{{- end }}