apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}-credentials
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  username: {{ .Values.config.username }}
  password: {{ .Values.config.password }}
