apiVersion: v1
kind: Secret
metadata:
  name: nvmesh-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
data:
  username: {{ .Values.config.username }}
  password: {{ .Values.config.password }}