apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: false