apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
  namespace: {{ template "nvmesh-csi-driver.namespace" . }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
