#
# NVMesh CSI Controller Driver StatefulSet Deployment
#
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nvmesh-csi-controller
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.serviceAccount.name }}
  selector:
    matchLabels:
      app: nvmesh-csi
  replicas: {{ .Values.controller.replicaCount }}
  template:
    metadata:
      labels:
        app: nvmesh-csi
    spec:
      serviceAccount: {{ .Values.serviceAccount.name }}
      containers:
        # NVMesh Driver
        - name: nvmesh-csi-driver
          # if we use image tag :latest kubernetes will try to fetch from Docker Hub (hub.docker.com)
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DRIVER_TYPE
              value: "Controller"
            - name: SOCKET_PATH
              value: unix:///csi/ctrl-csi.sock
            - name: MANAGEMENT_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-csi-config
                  key: management.servers
            - name: MANAGEMENT_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-csi-config
                  key: management.protocol
            - name: MANAGEMENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-credentials
                  key: username
            - name: MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-credentials
                  key: password
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
        # Provisioner
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.1.0
          args:
            - "--provisioner={{ .Values.driverName }}"
            - "--csi-address=/csi/ctrl-csi.sock"
            - "--v=5"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
        # Attacher
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=5"
            - "--csi-address=/csi/ctrl-csi.sock"
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
        # Resizer
        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:v0.1.0
          args:
            - "--v=5"
            - "--csi-address=/csi/ctrl-csi.sock"
            - "--leader-election"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi

      volumes:
        - name: plugin-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.driverName }}/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
---
#
# NVMesh Node Driver DaemonSet (Per Node) Deployment
#

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nvmesh-csi-node-driver
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: nvmesh-csi
  template:
    metadata:
      labels:
        app: nvmesh-csi
    spec:
      hostNetwork: true
      tolerations:
        # This would make the DaemonSet to be deployed also on the master node
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      containers:
        # NVMesh Driver
        - name: nvmesh-csi-driver
          # if we use image tag :latest kubernetes will try to fetch from Docker Hub (hub.docker.com)
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          env:
            - name: DRIVER_TYPE
              value: "Node"
            - name: SOCKET_PATH
              value: unix:///csi/csi.sock
            - name: MANAGEMENT_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-csi-config
                  key: management.servers
            - name: MANAGEMENT_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-csi-config
                  key: management.protocol
            - name: MANAGEMENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-credentials
                  key: username
            - name: MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-credentials
                  key: password
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: host-bin
              mountPath: /host/bin
            - name: var-opt-nvmesh
              mountPath: /var/opt/NVMesh
            - name: opt-nvmesh
              mountPath: /opt/NVMesh
        # Registrar
        - name: csi-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/{{ .Values.driverName }}/csi.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/{{ .Values.driverName }} /registration/{{ .Values.driverName }}-reg.sock"]
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: plugin-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.driverName }}/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        - name: host-bin
          hostPath:
            path: /bin
        - name: var-opt-nvmesh
          hostPath:
            path: /var/opt/NVMesh
        - name: opt-nvmesh
          hostPath:
            path: /opt/NVMesh