{{- if .Values.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "nvmesh-csi-driver.fullname" . }}
  labels:
{{ include "nvmesh-csi-driver.labels" . | indent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - 'SYS_ADMIN'
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'hostPath'
  hostNetwork: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
{{- end }}
