apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nvmesh-csi-driver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 12345
      name: dummy
  selector:
    {{- include "nvmesh-csi-driver.selectorLabels" . | nindent 4 }}
