apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
      containers:
      - name: c-1
        image: alpine:3
        command: ["/bin/sh", "-c", "echo hello ; while true ; do sleep 1; done"]
        volumeDevices:
            - name: vol
              devicePath: /vol
      restartPolicy: Never
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-1