apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-on-zone1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nvmesh-on-zone1
