kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nvmesh-on-zone1
provisioner: nvmesh-csi.excelero.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  vpg: DEFAULT_CONCATENATED_VPG
allowedTopologies:
- matchLabelExpressions:
  - key: nvmesh-csi.excelero.com/zone
    values:
    - Z1