kind: ConfigMap
apiVersion: v1
metadata:
  name: nvmesh-csi-driver-config
  namespace: test-csi-driver
  labels:
    app.kubernetes.io/name: nvmesh-csi-driver
    app.kubernetes.io/instance: nvmesh-csi-driver
data:
  management.protocol: https
  management.servers: 10.0.1.117:4000
  topology: |-
    {
       "type": "multiple-nvmesh-clusters",
       "zoneSelectionPolicy": "random",
       "zones":{
          "Z1":{
             "management": {
                "servers": "10.0.1.117:4000"
             }
          },
          "Z2":{
             "management": {
                "servers": "10.0.1.127:4000"
             }
          }
       }
    }