apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-encrypted-block
  labels:
    nvmesh-csi-testing: ""
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 3Gi
  storageClassName: encrypted-nvmesh-block