kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: encrypted-nvmesh-block
  labels:
    nvmesh-csi-testing: ""
provisioner: nvmesh-csi.excelero.com
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  vpg: DEFAULT_CONCATENATED_VPG
  encryption: dmcrypt
  csi.storage.k8s.io/node-stage-secret-name: dmcrypt-example-key
  csi.storage.k8s.io/node-stage-secret-namespace: nvmesh-csi
  dmcrypt/type: "luks2"
  dmcrypt/cipher: "aes-xts-plain64"
