#!/usr/bin/env python

import yaml


generated_yaml_file_comment = [
	"# DO NOT EDIT THIS FILE\n",
	"# This file is auto-generated by deploy/kubernetes/post_process_deployment.py\n"
]

k8s_api_compatibility = {
	'1.22': {
		'storage.k8s.io/v1beta1': 'storage.k8s.io/v1'
	},
	# '1.25': {
	# 	'policy/v1beta1': 'policy/v1'
	# }
}


def load_yaml_file(filename):
    with open(filename, 'r') as f:
        return list(yaml.safe_load_all(f))

def write_yaml_file(docs, output_file):
    with open(output_file, 'w') as f:
        f.writelines(generated_yaml_file_comment)
        yaml.dump_all(docs, f)

def get_deployment_for_k8s_version(k8s_version):
	deployment = load_yaml_file('../deployment.yaml')
	apis_to_update = k8s_api_compatibility[k8s_version]

	# filter out empty objects
	deployment = list(filter(lambda x: x, deployment))
	
	for obj in deployment:
		if not obj:
			continue
		old_api_version = obj.get('apiVersion')
		if old_api_version in apis_to_update:
			obj['apiVersion'] = apis_to_update[obj['apiVersion']]
			print('updated %s to %s for object %s' %(old_api_version, obj['apiVersion'], obj['metadata']['name']))

	return deployment

def create_deployment_files_for_newer_k8s_versions():
	for k8s_version in k8s_api_compatibility.keys():
		updated_deployment = get_deployment_for_k8s_version(k8s_version)
		new_deployment_file_name = '../deployment_k8s_%s.yaml' % k8s_version
		write_yaml_file(updated_deployment, new_deployment_file_name)

if __name__ == '__main__':
	create_deployment_files_for_newer_k8s_versions()
