apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-encrypted-xfs
  labels:
    nvmesh-csi-testing: ""
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: encrypted-nvmesh-xfs