
apiVersion: v1
kind: Pod
metadata:
  name: topology-pod-driven
spec:
  spec:
  affinity:
    # Here we make the Pod schedule to a specific zone
    # This will force the volume to be created in the selected zone
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvmesh-csi.excelero.com/zone
            operator: In
            values:
            - Z1
  containers:
    - name: alpine
      image: alpine
      volumeMounts:
      - name: vol
        mountPath: /vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: vol-wait-for-consumer