apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-wait-for-consumer
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nvmesh-wait-for-consumer
