---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nvmesh-jbod-xfs
  namespace: nvmesh-csi
provisioner: nvmesh-csi.excelero.com
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  vpg: DEFAULT_CONCATENATED_VPG
  fsType: xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvmesh-xfs
  namespace: nvmesh-csi-testing
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nvmesh-jbod-xfs
---