kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-custom-vpg-storage-class
provisioner: nvmesh-csi.excelero.com
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  vpg: my-nvmesh-vpg-name
  fsType: xfs